### ISSUE TITLE
Switch to mongosh

### ISSUE THREAD

**Issue by HOSTED-POWER** [m-erhardt/check-mongodb-plugins#1]
Hi, 

The mongo client has been deprecated.

Warning: the "mongo" shell has been superseded by "mongosh",
which delivers improved usability and compatibility.The "mongo" shell has been deprecated and will be removed in
an upcoming release.

Any chance your script could be updated to support it?

( I tried mongosh instead,  but atm it gives error when using with your plugin)

**Comment by m-erhardt** [comment]
Fixed in v1.0.0 (1bfce77)
